Dev
avalon-dev-j30/lab-1-ustinovsa pull request #1
Opened 2019-05-22 20:40 UTC by ustinovsa

@konivex 
Доброго времени суток!
Прошу проверить первую лабораторную работу.

2019-05-26 12:42 UTC, konivex requested changes
Исправьте замечание.

2019-05-26 12:42 UTC, konivex commented on src/ru/avalon/java/j30/labs/script.sql
> +    constraint ch_info_users check (info>0),
Эта проверка и аналогичная ch_roles_users ниже лишняя. 
Из определения ваших автоинкрементных колонок (в частности, в таблицах UserInfo и Role) следует, что отрицательных значений там не будет, а т.к. значения колонок info и roles являются внешними ключами, то в них смогут попасть только те значения, которые есть в колонках, на которые соответствующие ключи ссылаются.

2019-05-26 12:42 UTC, konivex commented on src/ru/avalon/java/j30/labs/script.sql
> +    constraint ch_orders_orders2products check (orders>0),
Аналогичное замечание тому, что оставлено выше.

2019-06-02 13:35 UTC, ustinovsa commented on src/ru/avalon/java/j30/labs/script.sql
> +    constraint ch_info_users check (info>0),
> Исправьте замечание.

@konivex 
замечания исправил

2019-06-02 20:45 UTC, konivex approved these changes
Смысла в максимальном значении 2147483647 для колонок initial_price и retail_value таблицы Product нет.

Зачтено.

2019-06-07 05:50 UTC, merged